version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: run-maven
          command: mvn sonar:sonar -Dsonar.projectKey=siegfried-ehret-sonarsource_svelte-private -Dsonar.organization=siegfried-ehret-sonarsource -Dsonar.host.url=https://sieg.eu.ngrok.io

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: SonarCloud
